### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'yalebinarysensor'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'yalebinarysensor'

### ISSUE THREAD

**Issue by darrenwaller** [mattinglis/YaleBinarySensor#2]
Hi,

I have just had the below reported by Home Assistant.

No 'version' key in the manifest file for custom integration 'yalebinarysensor'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'yalebinarysensor'

Hope you are aware of this.

Best regards,
Darren

**Comment by mattinglis** [comment]
Have updated the manifest.json to handle this change, no idea why a version should be compulsory, seems stupid, but hey ho.

**Comment by GTunney** [comment]
Hi,

I'm still getting this issue even after updating, any suggestions?
