### ISSUE TITLE
No 'version' key in the manifest file even after updating

### ISSUE THREAD

**Issue by GTunney** [mattinglis/YaleBinarySensor#3]
I'm still getting the no version error when starting HA even after updating Yale Binary Sensor.

I've checked the manifest.json and can see the version in there.

Any suggestions?

**Comment by darrenwaller** [comment]
Domain in the manifest.json needs to match the folder name in custom_components so should be set to yalebinarysensor

**Comment by GTunney** [comment]
> Domain in the manifest.json needs to match the folder name in custom_components so should be set to yalebinarysensor

I've changed domain to yalebinarysensor and still getting the same issue.

**Comment by darrenwaller** [comment]
Here is my manifest.json:

{
  "domain": "yalebinarysensor",
  "name": "Yale Custom Binary Sensors",
  "version": "1.2.0",
  "documentation": "https://github.com/mattinglis/YaleBinarySensor",
  "requirements": ["yalesmartalarmclient==0.1.7"],
  "dependencies": [],
  "codeowners": ["@mattinglis"]
}

This works fine for me.

**Comment by GTunney** [comment]
> Here is my manifest.json:
> 
> {
> "domain": "yalebinarysensor",
> "name": "Yale Custom Binary Sensors",
> "version": "1.2.0",
> "documentation": "https://github.com/mattinglis/YaleBinarySensor",
> "requirements": ["yalesmartalarmclient==0.1.7"],
> "dependencies": [],
> "codeowners": ["@mattinglis"]
> }
> 
> This works fine for me.

What an amateur. I changed it but mustn’t have clicked save 😂

thanks.
