### ISSUE TITLE
BinarySensors stopped working after core update 6.5

### ISSUE THREAD

**Issue by Vokke098213** [mattinglis/YaleBinarySensor#6]
Reason: No 'version' key in the manifest file for custom integration 'yalebinary'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'yalebinary' 11.58.33 – (ERROR) loader.py

Is it possible to fix this?

**Comment by mattinglis** [comment]
It is fixed, take the latest version or check closed issues for solutions

**Comment by Vokke098213** [comment]
Thanks!

In my case, it didn't work after update. Already had same domain and folder names in custom_components. Started working once I changed the platform from configuration.yaml yalebinary -> yalebinarysensor
