### ISSUE TITLE
cannot import name 'AuthenticationError' from 'yalesmartalarmclient.client' 

### ISSUE THREAD

**Issue by techcubs** [mattinglis/YaleBinarySensor#9]
Hi All,

does this still work, when i am trying this, i get the following:

Platform error binary_sensor.yalebinarysensor - cannot import name 'AuthenticationError' from 'yalesmartalarmclient.client' (/usr/local/lib/python3.9/site-packages/yalesmartalarmclient/client.py)

I have the files in my custom_component folder

and this is the config I have in configuration.yml:

binary_sensor:
  - platform: yalebinarysensor
    username: !secret hlgmail
    password: !secret yale_password
    additional_sensors: True
I also have the Yale Smart Living Integration that is working fine.

anybody else seeing this?

**Comment by htuomola** [comment]
Well I'm not seeing this error but the Home Assistant core yale integration breaks with a bit similar error
> Setup failed for yale_smart_alarm: Unable to import component: cannot import name 'UnknownError' from 'yalesmartalarmclient.exceptions' (/usr/local/lib/python3.9/site-packages/yalesmartalarmclient/exceptions.py)

The discussion [here](https://community.home-assistant.io/t/update-yale-smart-alarm-client/251949/109) suggests that the yalesmartalarmclient dependency of this library should be updated

**Comment by htuomola** [comment]
Ok I tried to update yalesmartalarmclient to version 0.3.8 for this library and the Core integration started, but now I get this same 'AuthenticationError' import error about this library.
... Oh but the Core HA integration seems to report at least door lock & contact sensor data now. Maybe I can disable this binary integration altogether.

**Comment by mattinglis** [comment]
I've updated it to fix these issues, but maybe the HA Authors have finally pulled it in to the core component
